# Generated by Django 3.1.3 on 2020-11-25 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import generator.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('column_separator', models.CharField(choices=[(',', 'Comma'), (';', 'Semicolon')], default=',', max_length=2)),
                ('string_character', models.CharField(choices=[('"', 'Double-quote'), ("'", 'Single-quote')], default='"', max_length=2)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=200)),
                ('column_type', models.CharField(choices=[('full_name', 'Full name'), ('job', 'Job'), ('email', 'Email'), ('phone_number', 'Phone number'), ('address', 'Address'), ('date', 'Date'), ('integer', 'Integer'), ('text', 'Text')], default='full_name', max_length=12)),
                ('order', generator.fields.OrderField(blank=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='generator.schema')),
            ],
        ),
    ]
