# Generated by Django 3.1.3 on 2020-11-26 12:44

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20201126_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='schema_columns',
        ),
        migrations.AddField(
            model_name='dataset',
            name='file',
            field=models.FileField(default=1, storage=django.core.files.storage.FileSystemStorage(location='static/csv_files'), upload_to=''),
            preserve_default=False,
        ),
    ]
